### ISSUE TITLE
Reinforced Cauldron is missing some lang entries

### ISSUE THREAD

**Issue by SiverDX** [Tfarcenim/Daves-Potioneering#22]
Forge, 1.19.2-1.2

Missing summary description:
![image](https://github.com/Tfarcenim/Daves-Potioneering/assets/22003703/8921150b-63de-4a33-a0f3-79b7c158cc00)

Jade has problems showing the name of the block:
![image](https://github.com/Tfarcenim/Daves-Potioneering/assets/22003703/49495e3d-04b4-4027-aa75-f867babf8103)

**Comment by Tfarcenim** [comment]
fixed

**Comment by DEAFG0AT** [comment]
This issue is still present on Fabric 1.19.2:
![2023-11-17_22 02 17](https://github.com/Tfarcenim/Daves-Potioneering/assets/104733108/72e7e61a-4326-4236-abc3-60fe8c5c4aea)
