### ISSUE TITLE
Item Render Crash

### ISSUE THREAD

**Issue by adam9899** [Tfarcenim/Daves-Potioneering#4]
Hi!
Ver Forge 1.16.5
Happens when opening the creative tab or searching in jei.

[crash-2022-10-16_23.28.27-client.txt](https://github.com/Tfarcenim/Daves-Potioneering/files/9795818/crash-2022-10-16_23.28.27-client.txt)

Thanks! really neat mod btw!

**Comment by Tfarcenim** [comment]
*Should* be fixed in 1.0.2

**Comment by PhweeDev** [comment]
This happens with 1.18.2 as well, it might happen with 1.19.2 as well. but specifically 1.18.2 for sure

**Comment by SplendidAlakey** [comment]
Yep, still happens in 1.19.2 Fabric/Quilt with REI as well, let me know if logs are needed.

Edit: actually it seems to happen even in the regular inventory/creative menu.
